# Generated by Django 5.0.4 on 2024-08-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_localisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gps',
            old_name='personneSuivi',
            new_name='personneSuivi_id',
        ),
    ]
