# Generated by Django 5.0.4 on 2024-08-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_localisation', '0002_rename_personnesuivi_gps_personnesuivi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='adr',
            field=models.CharField(default='adrese1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='prenom',
            field=models.CharField(default='jon', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='tel',
            field=models.CharField(default='0102050205', max_length=200),
            preserve_default=False,
        ),
    ]
